from typing import Protocol

from .models import AuthUser, AuthToken, User, UserUpdate


class AuthRepository(Protocol):
    async def get_user_by_id(self, id: str) -> AuthUser | None: ...


class ChallengeRepository(Protocol):
    async def save_challenge(self, id: str, challenge: bytes, ttl: int) -> None: ...
    async def get_challenge(self, id: str) -> bytes | None: ...
    async def delete_challenge(self, id: str) -> None: ...


class TokenProvider(Protocol):
    def create_token(self, user: AuthUser) -> AuthToken: ...


class UserRepository(Protocol):
    async def save(self, user: User, public_key: bytes) -> None: ...
    async def get_by_id(self, id: str) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_public_key_by_id(self, id: str) -> bytes | None: ...
    async def update(self, id: str, user_update: UserUpdate) -> User: ...
    async def exists_with_email(self, email: str) -> bool: ...


class IdentityProvider(Protocol):
    def generate(self) -> str: ...
