from typing import Protocol
from uuid import UUID
from .models import Project


class ProjectRepository(Protocol):
    async def get_projects_by_user_id(self, user_id: str) -> list[Project]: ...
    async def get_by_id(self, project_id: UUID) -> Project | None: ...


class ProjectStudentRepository(Protocol):
    async def get_student_ids(self, project_id: UUID) -> list[str]: ...
    async def add_student(self, project_id: UUID, student_id: str) -> None: ...
    async def remove_student(self, project_id: UUID, student_id: str) -> None: ...
    async def is_student_assigned(self, project_id: UUID, student_id: str) -> bool: ...


class IdentityService(Protocol):
    async def verify_student_exists(self, student_id: str) -> bool: ...
