repos:
 - repo: https://github.com/astral-sh/ruff-pre-commit
   rev: v0.13.1                                                                  
   hooks:                                                                        
     - id: ruff-check                                                            
       args: ["--fix"]
     - id: ruff-format

 - repo: https://github.com/pre-commit/mirrors-mypy          
   rev: v1.18.2                                                                  
   hooks:                                                                        
     - id: mypy                
       name: mypy-server
       files: ^server/                                                           
       args: ["--strict"]                                                        
       additional_dependencies: ["types-requests>=2.32.4.20250913"]
     - id: mypy                                                                                                                                                         
       name: mypy-client                                                                                                                                                
       files: ^client/                                                           
       additional_dependencies: ["types-requests>=2.32.4.20250913"]                                                                                                     
