repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.12
    hooks:
      - id: ruff
        name: "Ruff Check"
        args: ["--fix"]
      - id: ruff-format
        name: "Ruff Format"

  - repo: local
    hooks:
      - id: ty-apps
        name: "Typecheck: apps"
        entry: uv run ty check --fix apps/leader
        language: system
        types: [python]
        pass_filenames: false

      - id: ty-packages
        name: "Typecheck: packages"
        entry: uv run ty check --fix packages/
        language: system
        types: [python]
        pass_filenames: false
