from typing import Protocol
from uuid import UUID
from education_core.models import LabAttempt, AttemptListItem


class AttemptRepositoryPort(Protocol):
    async def save(self, attempt: LabAttempt) -> None: ...
    async def get_by_id(self, attempt_id: UUID) -> LabAttempt | None: ...
    async def find_by_student_and_project(
        self, student_id: str, project_id: UUID
    ) -> LabAttempt | None: ...
    async def get_by_submission_id(self, submission_id: UUID) -> LabAttempt | None: ...
    async def find_by_project(self, project_id: UUID) -> list[AttemptListItem]: ...
    async def update_grading(
        self, attempt_id: UUID, grade: int, feedback: str | None
    ) -> None: ...
