from typing import Protocol


class IdentityServicePort(Protocol):
    async def verify_student_exists(self, student_id: str) -> bool: ...
    async def verify_instructor_exists(self, instructor_id: str) -> bool: ...
