from typing import Protocol
from uuid import UUID
from education_core.models import Project, ProjectListItem


class ProjectRepositoryPort(Protocol):
    async def get_projects_by_user_id(self, user_id: str) -> list[ProjectListItem]: ...
    async def get_by_id(self, project_id: UUID) -> Project | None: ...
    async def exists_by_title(self, title: str) -> bool: ...
    async def save(self, project: Project) -> None: ...
    async def update(self, project: Project) -> None: ...
