from typing import Protocol
from uuid import UUID


class ManageStudentsPort(Protocol):
    async def get_students(self, project_id: UUID) -> list[str]: ...
    async def assign_student(self, project_id: UUID, student_id: str) -> None: ...
    async def remove_student(self, project_id: UUID, student_id: str) -> None: ...
