from typing import Protocol
from uuid import UUID
from ...models import LabSubmission, SubmissionStatus, SubmissionListItem


class SubmissionRepositoryPort(Protocol):
    async def save(self, submission: LabSubmission) -> None: ...
    async def find_by_id(self, submission_id: UUID) -> LabSubmission | None: ...
    async def find_by_student_and_project(
        self, student_id: str, project_id: UUID
    ) -> LabSubmission | None: ...
    async def list_by_project(self, project_id: UUID) -> list[SubmissionListItem]: ...
    async def update_status(
        self, submission_id: UUID, status: SubmissionStatus
    ) -> None: ...
