from typing import Protocol
from uuid import UUID


class ProjectStudentRepositoryPort(Protocol):
    async def get_student_ids(self, project_id: UUID) -> list[str]: ...
    async def add_student(self, project_id: UUID, student_id: str) -> None: ...
    async def remove_student(self, project_id: UUID, student_id: str) -> None: ...
    async def is_student_assigned(self, project_id: UUID, student_id: str) -> bool: ...
