from typing import Protocol


class ChallengeRepositoryPort(Protocol):
    async def save_challenge(self, id: str, challenge: bytes, ttl: int) -> None: ...
    async def get_challenge(self, id: str) -> bytes | None: ...
    async def delete_challenge(self, id: str) -> None: ...
